### ISSUE TITLE
Put a link to the issues page here for testers to leave feedback

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-client#8]
We did the first of our public debut sessions this morning. It might be good to display a little link/button to this issues page so that testers can leave us comment/bugs?

**Comment by NoisyFlowers** [comment]
I'd like to keep the pbot-api and pbot-client issues pages clean, with only legitimate bug reports or feature descriptions. I suggest the link on the site go to https://github.com/paleobot/pbot-dev/issues. This way, since that repo is kind of a catchall anyway, we can evaluate the stuff that comes in and route what isn't noise to the appropriate functional piece of the project.

**Comment by NoisyFlowers** [comment]
This is implemented as a sticky footer. It is in 4bc8151adf310bfbc90cb1fa978ecdebb7e2f064.
